version: "3.8"

services:
  billing-service:
    image: billing-service
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
    - SERVER_PORT=4001

    ports:
      - "4001:4001"
      - "9001:9001"
    restart: always
